name: ReleaseAndBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-bot:
    name: Build Project and Upload Artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build PhipseyyBot --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish Linux-arm64
        run: dotnet publish PhipseyyBot -r linux-arm64 -p:PublishSingleFile=true --self-contained

      - name: Publish Linux-x64
        run: dotnet publish PhipseyyBot -r linux-x64 -p:PublishSingleFile=true --self-contained

      - name: Publish Win-x64
        run: dotnet publish PhipseyyBot -r win-x64 -p:PublishSingleFile=true --self-contained

      - name: Upload Linux-arm64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Artifact_linux-arm64
          path: PhipseyyBot/bin/Release/net8.0/linux-arm64/publish/

      - name: Upload Linux-x64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Artifact_linux-x64
          path: PhipseyyBot/bin/Release/net8.0/linux-x64/publish/

      - name: Upload Win-x64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Artifact_win-x64
          path: PhipseyyBot/bin/Release/net8.0/win-x64/publish/

  release-bot:
    name: Create Release and Upload Assets
    runs-on: ubuntu-latest
    needs: build-bot
    permissions:
      contents: write
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Create Tag
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          tag_name="v0.0.${{ github.run_number }}"
          git tag $tag_name
          git push origin $tag_name

      - name: Download Linux-arm64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: Artifact_linux-arm64
          path: linux-arm64

      - name: Download Linux-x64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: Artifact_linux-x64
          path: linux-x64

      - name: Download Win-x64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: Artifact_win-x64
          path: win-x64

      - name: Zip Artifacts
        run: |
          zip -r linux-arm64.zip linux-arm64/ -x "*.pdb"
          zip -r linux-x64.zip linux-x64/ -x "*.pdb"
          zip -r win-x64.zip win-x64/ -x "*.pdb"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.0.${{ github.run_number }}
          files: |
            linux-arm64.zip
            linux-x64.zip
            win-x64.zip
          name: Release v0.0.${{ github.run_number }}