name: ReleaseAndBuild

on:
  push:
    tags:
      - '*'
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    

jobs:
  release-project:
    name: Release to Github
    runs-on: ubuntu-latest
    needs: build-project
    steps:
    - name: Download site content
      uses: actions/download-artifact@v2
      with:
        name: site-build
      
    - name: View content
      run: ls -R
      
    - name: Create GitHub release
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
    
    - name: Archive site content
      uses: thedoctor0/zip-release@master
      with:
        filename: site.zip
        
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./site.zip
        asset_name: site-v${{ github.run_number }}.zip
        asset_content_type: application/zip
    
  build-project:
    name: build_release
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build PhipseyyBot --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish Linux-ARM64
      run: dotnet publish PhipseyyBot -r linux-arm64 -p:PublishSingleFile=true --self-contained 
      
    - name: Publish Win-X64
      run: dotnet publish PhipseyyBot -r win-x64 -p:PublishSingleFile=true --self-contained
      
    - name: Upload Build Linux-ARM64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Artifact_linux-x64
        path: /home/runner/work/PhipseyyBot/PhipseyyBot/PhipseyyBot/bin/Debug/net6.0/linux-arm64/publish/
        
    - name: Upload Build Win-x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Artifact_win-x64
        path: /home/runner/work/PhipseyyBot/PhipseyyBot/PhipseyyBot/bin/Debug/net6.0/win-x64/publish/


  
        
   
